# General Settings
set -g default-terminal 'screen-256color'
set -g status-position bottom
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -sg escape-time 0
set -g focus-events on
set -g set-clipboard on

# Prefix Key
unbind C-b
set -g prefix C-b
bind C-b send-prefix

# Display
set -g status-interval 5
set -g status-justify left
set -g status-style 'fg=#f8f8f2,bg=#44475a'
set -g message-style 'fg=#282a36,bg=#8be9fd'
set -g pane-border-style 'fg=#6272a4'
set -g pane-active-border-style 'fg=#50fa7b'
set -g mode-style 'fg=#282a36,bg=#bd93f9'
set -g status-left-length 100
set -g status-right-length 120

# Status Bar Left/Right
set -g status-left '#[fg=#111216,bg=#bd93f9,bold] #[nobold]#I:#W '
set -g status-right '#[fg=#111216,bg=#bd93f9,bold] #[nobold]%Y-%m-%d %H:%M #[fg=#111216,bg=#8be9fd,bold] #[nobold]#(hostname | cut -d- -f1) '

# Window Status
setw -g window-status-format '#[fg=#f8f8f2,bg=#6272a4] #I:#W '
setw -g window-status-current-format '#[fg=#1f1f28,bg=#ff79c6,bold] #I:#W '

# Colors
set -as terminal-overrides ',*:Tc'

# Key Bindings
bind r source-file ~/.tmux.conf \; display-message 'Config reloaded'
bind | split-window -h
bind - split-window -v

